project:
  name: quickstart-bitnami-wordpress
  owner: abjimenez@bitnami.com
  package_lambda: false
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  parameters:
    ALBAccessCIDR: 10.0.0.0/16
    AutoScalingNotificationEmail: foo@example.com
    AvailabilityZones: $[taskcat_genaz_2]
    BastionAMIOS: Amazon-Linux-HVM
    BastionInstanceType: t2.micro
    DBAutoMinorVersionUpgrade: 'true'
    DBBackupRetentionPeriod: '7'
    DBInstanceClass: db.t2.small
    DBMasterUserPassword: $[taskcat_genpass_16A]
    DBMultiAZ: 'true'
    DBPreferredBackupWindow: ''
    KeyPairName: $[taskcat_getkeypair]
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    RemoteAccessCIDR: 10.0.0.0/16
    VPCCIDR: 10.0.0.0/16
    WebServerDesiredCapacity: '2'
    WebServerInstanceMonitoring: Enabled
    WebServerInstanceType: t2.small
    WebServerMaxSize: '3'
    WebServerMinSize: '2'
    WordpressAdminPassword: $[taskcat_genpass_16A]
tests:
  bitnami-wordpress:
    template: templates/wordpress-master.template
